// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA24qLsuh1_owsV0lzLJnWcP04m31D4584',
    appId: '1:373621730772:web:22d4338966b0275c2a7a41',
    messagingSenderId: '373621730772',
    projectId: 'healthlogger-app',
    authDomain: 'healthlogger-app.firebaseapp.com',
    storageBucket: 'healthlogger-app.appspot.com',
    measurementId: 'G-YWYYP3SJXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmBjzvS_DmTUo9-FqJ3FvmiufKjJieuVI',
    appId: '1:373621730772:android:7504586eb7f8d0d82a7a41',
    messagingSenderId: '373621730772',
    projectId: 'healthlogger-app',
    storageBucket: 'healthlogger-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoYNxhTXZt66IYoepglRvglgowOUowvQo',
    appId: '1:373621730772:ios:0b1155fca9635ebd2a7a41',
    messagingSenderId: '373621730772',
    projectId: 'healthlogger-app',
    storageBucket: 'healthlogger-app.appspot.com',
    iosBundleId: 'com.example.demoFlutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoYNxhTXZt66IYoepglRvglgowOUowvQo',
    appId: '1:373621730772:ios:0b1155fca9635ebd2a7a41',
    messagingSenderId: '373621730772',
    projectId: 'healthlogger-app',
    storageBucket: 'healthlogger-app.appspot.com',
    iosBundleId: 'com.example.demoFlutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA24qLsuh1_owsV0lzLJnWcP04m31D4584',
    appId: '1:373621730772:web:50d5ff7f9fa6fef32a7a41',
    messagingSenderId: '373621730772',
    projectId: 'healthlogger-app',
    authDomain: 'healthlogger-app.firebaseapp.com',
    storageBucket: 'healthlogger-app.appspot.com',
    measurementId: 'G-1PF8WN3QKQ',
  );
}
